---
- name: Breakfast
  image_path: "/uploads/26e35572a7a86c86fa18093679fbd4e1-2.jpg"
- name: Burritos
  image_path: "/uploads/burrito.jpg"
- name: Desserts
  image_path: "/uploads/flan.jpg"
- name: Drinks
  image_path: "/uploads/drink.jpg"
- name: Fruit Bowls
  image_path: "/uploads/fruitbowl.jpg"
- name: Platillos
  image_path: "/uploads/placeholder.jpg"
- name: Salads
  image_path: "/uploads/salad.jpg"
- name: Sandwiches
  image_path: "/uploads/placeholder.jpg"
- name: Tacos
  image_path: "/uploads/placeholder.jpg"
- name: Tortas
  image_path: "/uploads/torta.jpg"
- name: Tostadas
  image_path: "/uploads/placeholder.jpg"