---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: Config
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: product_cat_pages
  label: Product Categories
  create: documents
  match: "**/*"
  new_doc_ext: html
- type: directory
  path: _products
  label: Products
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
