---
label: Product Categories
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: Category Name
- name: hero
  label: Hero
  type: text
  hidden: false
  default: Category Name
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: Wow this stuff is great!
- name: permalink
  label: Permalink
  type: text
  hidden: false
  default: ''
