---
label: Product Categories
hide_body: 
is_partial: 
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: hero
  label: Hero
  type: text
  hidden: false
  default: ''
- name: subtitle
  label: Subtitle
  type: text
  hidden: false
  default: ''
- name: permalink
  label: Permalink
  type: text
  hidden: false
  default: ''
